version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: Semantle
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./mongo-volume:/data/db
  redis:
        container_name: redis
        command: bash -c "redis-server --appendonly yes"
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./redis-volume:/data

  web_app:
    container_name: web_app
    build:
      dockerfile: Dockerfile
      context: .
    image: semantle/fastapi
    depends_on:
      - mongodb
      - redis
    ports:
      - "5000:5000"